name: Keep Render Backend Alive

on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Endpoints
        run: |
          curl -s https://dragon-ball-api-grlr.onrender.com/random
          curl -s https://dragon-ball-api-6yp5.onrender.com/random 
          curl -s https://nutrition-calculator-hvzj.onrender.com/test123
          curl -s https://go-chatbot-backend.onrender.com/test
